config/routes.rb
Rails.application.routes.draw do

  
  root 'welcome#index'
  get 'audio', to: 'welcome#audio'
  get 'contacto', to: 'welcome#contacto'
  
  get  'contact_mail', to: 'contactmail#new'
  post 'contact_mail', to: 'contactmail#send'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
      
  end
  
  def audio
      
  end
  
  def contacto
      
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navegacion.html.erb
<!-- Navbar -->
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="#">Me</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li> <%= link_to "INICIO", root_path %> </li>
        <li><%= link_to "AUDIOS", audio_path %></li>
        <li><%= link_to "CONTACTAME", contacto_path %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_piepagina.html.erb
<!-- Footer -->
<footer class="container-fluid bg-4 text-center">
  <p>Copyright @ 2017 - Charlot Prins - Actriz de voz - Venezuela.</p>
  
            <a href="https://www.facebook.com/charlotprins"><i id="social-fb" class="fa fa-facebook-square fa-3x social"></i></a>
	        <a href="https://twitter.com/charlotprins"><i id="social-tw" class="fa fa-twitter-square fa-3x social"></i></a>
	        <a href="https://plus.google.com/+Bootsnipp-page"><i id="social-gp" class="fa fa-google-plus-square fa-3x social"></i></a>
	        <a href="mailto:charlotprins@gmail.com"><i id="social-em" class="fa fa-envelope-square fa-3x social"></i></a>
	        <a href="https://www.linkedin.com/in/charlotprins/"><i id="social-tw" class="fa fa-linkedin-square fa-3x social"></i></a>
	        <a href="https://plus.google.com/+Bootsnipp-page"><i id="social-gp" class="fa fa-youtube-square fa-3x social"></i></a>
	        <p><span class="glyphicon glyphicon-phone"></span> +58-412-555-5555 </p>
</footer>

app/views/layouts/application.html.1.erb
<!DOCTYPE html>
<html>
<head>
  <title>WebpageCharlot</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  

</head>

<body style="background-color:gray;">
  
<!-- <%= render 'layouts/navegacion' %>  -->
<%= yield %>
<!-- <%= render 'layouts/piepagina' %>   -->


</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WebpageCharlot</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  

</head>

<body style="background-color:gray;">
  
<%= render 'layouts/navegacion' %>  
<%= yield %>
<%= render 'layouts/piepagina' %>  


</body>
</html>

app/views/welcome/audio.html.erb
<!-- First Container -->
<!--  <h3 class="margin">Who Am I?</h3>
  <h3>I'm an adventurer</h3>-->
  <div class="container">
    <br>
    <h2>Audios</h2>
    <div class="w3-card-4" style="width:100%">
      <%=image_tag "imagen-audio.jpg",:class => "img-responsive margin" ,:style =>"width:100%", :alt =>"Image"%>
      <div class="w3-container" style="padding-left:40px;padding-right:40px">
        <h4 class="padding-top:0px">Audios 1</h4>
        <%= audio_tag( "horse.ogg", controls: true)%>
        <%= audio_tag( "horse.ogg", controls: true)%>
      </div>
      
      <div class="w3-container" style="padding-left:40px;padding-right:40px">
        <h4>Audios 2</h4>
        <%= audio_tag( "horse.ogg", controls: true)%>
        <%= audio_tag( "horse.ogg", controls: true)%>
        <%= audio_tag( "horse.ogg", controls: true)%>
      </div>
      
      <div class="w3-container" style="padding-left:40px;padding-right:40px">
        <h4>Audio 3</h4>
        <%= audio_tag( "horse.ogg", controls: true )%>
      </div>
      
      <div class="w3-container" style="padding-left:40px;padding-right:40px">
        <h4>Audios 4</h4>
        <%= audio_tag( "horse.ogg", controls: true )%>
        <%= audio_tag( "horse.ogg", controls: true)%>
        <%= audio_tag( "horse.ogg", controls: true)%>
        <%= audio_tag( "horse.ogg", controls: true)%>
      </div>
      
      <div  align="center">
		    <div>
			    <iframe width="93%"  scrolling="no"  src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/247279571&amp;color=52A9A3&amp;auto_play=true&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false" ></iframe>
		    </div>
	    </div>
      <br>
    </div>
    <br>
  </div>


    
 
  

app/views/welcome/contacto.html.erb
 <div class="container">
    <br>
    <h2>Contáctame</h2>
    <div class="w3-card-4" style="width:100%">
      <%=image_tag "banner-contacto.jpg",:class => "img-responsive margin" ,:style =>"width:100%", :alt =>"Image"%>
        <%= form_for(:session, :html => {class: "form-horizontal", role: "form"}, url: contact_mail_path) do |f|  %>
        <div class="form-group">
          <div class="control-label col-sm-2">
            <%= f.label "Nombre"  %>
          </div> 
          <div class="col-sm-9">
            <%= f.text_field :apikey, class: "form-control", placeholder: "Ingresa tu nombre", autofocus: true, required: true %>
          </div>
        </div>
        <div class="form-group">
          <div class="control-label col-sm-2">
            <%= f.label "E-Mail"  %> <br/>
          </div>
          <div class="col-sm-6">
            <%= f.email_field :email, class: "form-control", placeholder: "Ingresa tu dirección de correo electrónico", required: true %>
          </div>
        </div>
        <div class="form-group">
          <div class="control-label col-sm-2">
            <%= f.label "Mensaje"  %> <br/>
          </div>
          <div class="col-sm-9">
            <%= f.text_area :message, class: "form-control", rows: 10, placeholder: "Ingresa tu mensaje", required: true %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">  
            <%= f.submit "Enviar", class: 'btn btn-primary btn-lg'%> 
          </div>
        </div>
        <br>
        <% end %>
    </div>
    <br>
  </div>

app/views/welcome/index.html.1.erb
<!-- First Container -->
<div class="container-fluid bg-1 text-center">
<!--  <h3 class="margin">Who Am I?</h3>
  <h3>I'm an adventurer</h3>-->
</div>

<!-- Second Container -->
<div class="container-fluid bg-2 text-center">
  <h1 class="margin">Bienvenidos</h1>
  <br/>
  <h4>Yo tengo tu voz...! </h4>
 <!-- <a href="#" class="btn btn-default btn-lg">
    <span class="glyphicon glyphicon-search"></span> Search
  </a>-->
  
  <!-- Grid -->
  <div class="w3-row-padding" id="about">
    <!--<div class="w3-center w3-padding-64">
      <span class="w3-xlarge w3-bottombar w3-border-dark-grey w3-padding-16">Who We Are</span>
    </div>-->

    <div class="w3-third w3-margin-bottom prueba">
      <div class="w3-card-4">
        <%=image_tag "homeimage.jpg",:class => "img-responsive margin" ,:style =>"width:100%", :alt =>"Image"%>
        <div class="w3-container ">
          <h3>Jane Doe</h3>
          <p class="w3-opacity">CEO & Founder</p>
          <p>Phasellus eget enim eu lectus faucibus vestibulum. Suspendisse sodales pellentesque elementum.</p>
        </div>
      </div>
    </div>

    <div class="w3-third w3-margin-bottom prueba">
      <div class="w3-card-4">
        <%=image_tag "homeimage.jpg",:class => "img-responsive margin" ,:style =>"width:100%", :alt =>"Image"%>
        <div class="w3-container">
          <h3>Mike Ross</h3>
          <p class="w3-opacity">Art Director</p>
          <p>Phasellus eget enim eu lectus faucibus vestibulum. Suspendisse sodales pellentesque elementum.</p>
        </div>
      </div>
    </div>

    <div class="w3-third w3-margin-bottom prueba">
      <div class="w3-card-4">
        <%=image_tag "homeimage.jpg",:class => "img-responsive margin" ,:style =>"width:100%", :alt =>"Image"%>
        <div class="w3-container">
          <h3>John Doe</h3>
          <p class="w3-opacity">Designer</p>
          <p>Phasellus eget enim eu lectus faucibus vestibulum. Suspendisse sodales pellentesque elementum.</p>
        </div>
      </div>
    </div>
  </div>
  
</div>

<!-- Third Container (Grid) -->
<div class="container-fluid bg-3 text-center">    
  <h3 class="margin">Where To Find Me?</h3><br>
  <div class="row">
    <div class="col-sm-4">
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
      <%=image_tag "bird.jpg",:class => "img-responsive margin" ,:style =>"width:100%", :alt =>"Image"%>
    </div>
    <div class="col-sm-4"> 
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
      <%=image_tag "bird.jpg",:class => "img-responsive margin" ,:style =>"width:100%", :alt =>"Image"%>
    </div>
    <div class="col-sm-4"> 
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
      <%=image_tag "bird.jpg",:class => "img-responsive margin" ,:style =>"width:100%", :alt =>"Image"%>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<H1> EN CONSTRUCCION .. CHARLOT WEBPAGE</H1>